[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "common"
requires-python = ">= 3.12"
version = "1.0"
dependencies = [
    "PyJWT == 2.8.0",
    "pyjwt[crypto]"
]