apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cs3900-database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-bookworm
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: cs3900-oci-sc
      volumeMode: Filesystem
  resources:
    requests:
      memory: "1.5Gi"
      cpu: "250m"
    limits:
      memory: "3Gi"
      cpu: "500m"
