apiVersion: v1
kind: Service
metadata:
  name: cs3900-svc
  labels:
    app.kubernetes.io/name: cs3900
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: cs3900
